language: cpp
sudo: required
matrix:
        include:
        - compiler: gcc
                addons: 
                        apt:
                                sources:
                                - ubuntu-toolchain-r-test
                                packages:    
                                - gcc-4.8
                                - g++-4.8
matrix:
        include:
        - compiler: gcc
                addons: 
                        apt:
                                sources:
                                - ubuntu-toolchain-r-test
                                packages:    
                                - gcc-5.0
                                - g++-5.0

before_script:
- sudo apt-get update -qq
- sudo apt-get install -y libblkid-dev
- sudo apt-get install -y libudev-dev
- sudo apt-get install -y libqt4-dev
- sudo apt-get install -y kdebase-workspace-dev
- sudo apt-get install -y libqjson-dev
script:
- mkdir build && cd build && cmake -Dkde=4 .. && make
notifications:
  email:
  - iddekingej@lycos.com
