language: cpp
g++:
- 5.0
- 4.8
- 4.7
- 4.6
sudo: required

before_script:
- sudo apt-get update -qq
- sudo apt-get install -y libblkid-dev
- sudo apt-get install -y libudev-dev
- sudo apt-get install -y libqt4-dev
- sudo apt-get install -y kdebase-workspace-dev
- sudo apt-get install -y libqjson-dev
script:
- mkdir build && cd build && cmake -D kde4 .. && make
notifications:
  email:
  - iddekingej@lycos.com
