language: cpp
g++:
- 5.0
- 4.8
- 4.7
- 4.6
sudo: required

before_script:
- sudo apt-get update -qq
- sudo apt-get install libblkid1 libblkid-dev
script:
- mkdir build && cd build && cmake .. && make
